### ISSUE TITLE
Rendering any model with mirrored UVs seems to be broken.

### ISSUE THREAD

**Issue by fallahn** [Zone-organization/Nuclear-Engine#9]
I noticed this in your readme - I haven't tried your engine (yet) but I had a similar issue once in my own project. The fix was simply to use GL_REPEAT instead of GL_CLAMP_TO_EDGE for the texture wrap mode. Maybe this is the case here?

**Comment by v7medz** [comment]
Thanks very much! It fixed the issue.

+ When porting to Diligent I chose to automate the creation for samplers due to restrictions that Diligent API put in order to support new APIs (DX12, Vulkan), and all the created sampler were Clamp_To_Edge type, Thats why I didnt notice it. :D anyway I will begin working on Supporting separate samplers instead of automating their creation.

Thanks again!
